<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>dev.simon</groupId>
  <artifactId>MontageWorkflow2.0</artifactId>
  <version>1.0</version>
  <properties>
    <maven.compiler.target>17</maven.compiler.target>
    <exec.mainClass>dev.simon.Main</exec.mainClass>
    <maven.compiler.source>17</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    <dependency>
      <groupId>dev.simon</groupId>
      <artifactId>Montage</artifactId>
      <version>2.0</version>
    </dependency>
    <dependency>
      <groupId>dev.simon</groupId>
      <artifactId>DirectoryMonitor</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>dev.simon</groupId>
      <artifactId>FissionLessPathUtil</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.10.1</version>
    </dependency>
    <dependency>
      <groupId>dev.simon</groupId>
      <artifactId>DirectoryMonitor</artifactId>
      <version>1.0</version>
    </dependency>
    <dependency>
      <groupId>dev.simon</groupId>
      <artifactId>JStorage</artifactId>
      <version>2.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud.functions</groupId>
      <artifactId>functions-framework-api</artifactId>
      <version>1.1.0</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.5.0</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
              </transformers>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <finalName>split-function</finalName>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
