from modules.Scheduler import Scheduler

def main():
    scheduler = Scheduler(
        path_to_function_csv="",        # path to the functions.csv generated by preprocess.py
        path_to_file_transfer_csv="",   # path to the file_transfers.csv generated by preprocess.py
        path_to_workflow_config="",     # path to the workflowConfig.json
        theta=6                         # defines the theta value    
    )

    scheduler.optimize_cost_performance() # determines the optimal cost performance
    scheduler.update_split_function_config(output_path="") # path to store the updated workflowConfig.json
    
    # For other experiment setups like Sizeless Sonic or Fado
    # scheduler.print_minimal_cost_info() # prints the minimal for the workflow
    # scheduler.print_minimal_memory_info() # prints the minimal memory for the workflow
    # scheduler.print_minimal_runtime_info() # prints the minimal runtime for the workflow

if __name__ == "__main__":
    main()
